/**
 * @type {import('@remix-run/dev').AppConfig}
 */
module.exports = {
  ignoredRouteFiles: [".*"],
  appDirectory: "app",
  assetsBuildDirectory: "public/build",
  // serverBuildPath: "build/index.js",
  publicPath: "/build/",
  serverBuildDirectory: "build",
  // serverDependenciesToBundle: [
  //   "@withneutron/ui",
  //   "@loadable/component",
  //   "@react-types/shared",
  //   "@react-aria/button",
  //   "@react-aria/checkbox",
  //   "@react-aria/focus",
  //   "@react-aria/interactions",
  //   "@react-aria/numberfield",
  //   "@react-aria/radio",
  //   "@react-aria/searchfield",
  //   "@react-aria/select",
  //   "@react-aria/ssr",
  //   "@react-aria/switch",
  //   "@react-aria/tabs",
  //   "@react-aria/textfield",
  //   "@react-aria/utils",
  //   "@react-stately/numberfield",
  //   "@react-stately/searchfield",
  //   "@stitches/react",
  //   "chroma-js",
  //   "locale-enum",
  //   "react",
  //   "react-helmet",
  //   "react-icons",
  //   "react-laag",
  //   "react-walk-element-tree",
  // ],
}
